//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImportError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportError() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ImportError", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 组织架构不能为空 的本地化字符串。
        /// </summary>
        internal static string err_010100 {
            get {
                return ResourceManager.GetString("err_010100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织架构不存在 的本地化字符串。
        /// </summary>
        internal static string err_010101 {
            get {
                return ResourceManager.GetString("err_010101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配到多个组织架构 的本地化字符串。
        /// </summary>
        internal static string err_010102 {
            get {
                return ResourceManager.GetString("err_010102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户编号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_010200 {
            get {
                return ResourceManager.GetString("err_010200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_010300 {
            get {
                return ResourceManager.GetString("err_010300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户地址不能为空 的本地化字符串。
        /// </summary>
        internal static string err_010400 {
            get {
                return ResourceManager.GetString("err_010400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人不能为空 的本地化字符串。
        /// </summary>
        internal static string err_010500 {
            get {
                return ResourceManager.GetString("err_010500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话不能为空 的本地化字符串。
        /// </summary>
        internal static string err_010600 {
            get {
                return ResourceManager.GetString("err_010600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售渠道不能为空 的本地化字符串。
        /// </summary>
        internal static string err_010700 {
            get {
                return ResourceManager.GetString("err_010700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售渠道不存在 的本地化字符串。
        /// </summary>
        internal static string err_010701 {
            get {
                return ResourceManager.GetString("err_010701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配到多个销售渠道 的本地化字符串。
        /// </summary>
        internal static string err_010702 {
            get {
                return ResourceManager.GetString("err_010702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不能为空 的本地化字符串。
        /// </summary>
        internal static string err_010800 {
            get {
                return ResourceManager.GetString("err_010800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不存在 的本地化字符串。
        /// </summary>
        internal static string err_010801 {
            get {
                return ResourceManager.GetString("err_010801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户等级不存在 的本地化字符串。
        /// </summary>
        internal static string err_010901 {
            get {
                return ResourceManager.GetString("err_010901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行政架构不存在 的本地化字符串。
        /// </summary>
        internal static string err_011001 {
            get {
                return ResourceManager.GetString("err_011001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配到多个行政架构 的本地化字符串。
        /// </summary>
        internal static string err_011002 {
            get {
                return ResourceManager.GetString("err_011002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连锁集团不存在 的本地化字符串。
        /// </summary>
        internal static string err_011100 {
            get {
                return ResourceManager.GetString("err_011100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机不能为空 的本地化字符串。
        /// </summary>
        internal static string err_011200 {
            get {
                return ResourceManager.GetString("err_011200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_020100 {
            get {
                return ResourceManager.GetString("err_020100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_020200 {
            get {
                return ResourceManager.GetString("err_020200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品简称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_020300 {
            get {
                return ResourceManager.GetString("err_020300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在 的本地化字符串。
        /// </summary>
        internal static string err_020400 {
            get {
                return ResourceManager.GetString("err_020400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在 的本地化字符串。
        /// </summary>
        internal static string err_020500 {
            get {
                return ResourceManager.GetString("err_020500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在 的本地化字符串。
        /// </summary>
        internal static string err_020600 {
            get {
                return ResourceManager.GetString("err_020600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在 的本地化字符串。
        /// </summary>
        internal static string err_020700 {
            get {
                return ResourceManager.GetString("err_020700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在 的本地化字符串。
        /// </summary>
        internal static string err_020800 {
            get {
                return ResourceManager.GetString("err_020800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在 的本地化字符串。
        /// </summary>
        internal static string err_020900 {
            get {
                return ResourceManager.GetString("err_020900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在 的本地化字符串。
        /// </summary>
        internal static string err_021000 {
            get {
                return ResourceManager.GetString("err_021000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在 的本地化字符串。
        /// </summary>
        internal static string err_021100 {
            get {
                return ResourceManager.GetString("err_021100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在 的本地化字符串。
        /// </summary>
        internal static string err_021200 {
            get {
                return ResourceManager.GetString("err_021200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品类型不能为空 的本地化字符串。
        /// </summary>
        internal static string err_021300 {
            get {
                return ResourceManager.GetString("err_021300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品类型不存在 的本地化字符串。
        /// </summary>
        internal static string err_021301 {
            get {
                return ResourceManager.GetString("err_021301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不能为空 的本地化字符串。
        /// </summary>
        internal static string err_021400 {
            get {
                return ResourceManager.GetString("err_021400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不存在 的本地化字符串。
        /// </summary>
        internal static string err_021401 {
            get {
                return ResourceManager.GetString("err_021401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_030100 {
            get {
                return ResourceManager.GetString("err_030100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名不能为空 的本地化字符串。
        /// </summary>
        internal static string err_030200 {
            get {
                return ResourceManager.GetString("err_030200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户职位不存在 的本地化字符串。
        /// </summary>
        internal static string err_030300 {
            get {
                return ResourceManager.GetString("err_030300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户角色不能为空 的本地化字符串。
        /// </summary>
        internal static string err_030400 {
            get {
                return ResourceManager.GetString("err_030400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户角色不存在 的本地化字符串。
        /// </summary>
        internal static string err_030401 {
            get {
                return ResourceManager.GetString("err_030401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织架构不能为空 的本地化字符串。
        /// </summary>
        internal static string err_030500 {
            get {
                return ResourceManager.GetString("err_030500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织架构不存在 的本地化字符串。
        /// </summary>
        internal static string err_030501 {
            get {
                return ResourceManager.GetString("err_030501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配到多个组织架构 的本地化字符串。
        /// </summary>
        internal static string err_030502 {
            get {
                return ResourceManager.GetString("err_030502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入职日期格式不正确 的本地化字符串。
        /// </summary>
        internal static string err_030600 {
            get {
                return ResourceManager.GetString("err_030600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离职日期格式不正确 的本地化字符串。
        /// </summary>
        internal static string err_030700 {
            get {
                return ResourceManager.GetString("err_030700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门不存在 的本地化字符串。
        /// </summary>
        internal static string err_030801 {
            get {
                return ResourceManager.GetString("err_030801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配到多个部门 的本地化字符串。
        /// </summary>
        internal static string err_030802 {
            get {
                return ResourceManager.GetString("err_030802", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分销列表名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_040100 {
            get {
                return ResourceManager.GetString("err_040100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户编号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_040200 {
            get {
                return ResourceManager.GetString("err_040200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户不存在 的本地化字符串。
        /// </summary>
        internal static string err_040300 {
            get {
                return ResourceManager.GetString("err_040300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_040400 {
            get {
                return ResourceManager.GetString("err_040400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不能为空 的本地化字符串。
        /// </summary>
        internal static string err_040500 {
            get {
                return ResourceManager.GetString("err_040500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不存在 的本地化字符串。
        /// </summary>
        internal static string err_040600 {
            get {
                return ResourceManager.GetString("err_040600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分销列表名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_050100 {
            get {
                return ResourceManager.GetString("err_050100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_050200 {
            get {
                return ResourceManager.GetString("err_050200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品不存在 的本地化字符串。
        /// </summary>
        internal static string err_050300 {
            get {
                return ResourceManager.GetString("err_050300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_050400 {
            get {
                return ResourceManager.GetString("err_050400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不能为空 的本地化字符串。
        /// </summary>
        internal static string err_050500 {
            get {
                return ResourceManager.GetString("err_050500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不存在 的本地化字符串。
        /// </summary>
        internal static string err_050600 {
            get {
                return ResourceManager.GetString("err_050600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分销列表名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_060100 {
            get {
                return ResourceManager.GetString("err_060100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色编号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_060200 {
            get {
                return ResourceManager.GetString("err_060200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色不存在 的本地化字符串。
        /// </summary>
        internal static string err_060300 {
            get {
                return ResourceManager.GetString("err_060300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_060400 {
            get {
                return ResourceManager.GetString("err_060400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不能为空 的本地化字符串。
        /// </summary>
        internal static string err_060500 {
            get {
                return ResourceManager.GetString("err_060500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不存在 的本地化字符串。
        /// </summary>
        internal static string err_060600 {
            get {
                return ResourceManager.GetString("err_060600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分销列表名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_070100 {
            get {
                return ResourceManager.GetString("err_070100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_070200 {
            get {
                return ResourceManager.GetString("err_070200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品不存在 的本地化字符串。
        /// </summary>
        internal static string err_070300 {
            get {
                return ResourceManager.GetString("err_070300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_070400 {
            get {
                return ResourceManager.GetString("err_070400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不能为空 的本地化字符串。
        /// </summary>
        internal static string err_070500 {
            get {
                return ResourceManager.GetString("err_070500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不存在 的本地化字符串。
        /// </summary>
        internal static string err_070600 {
            get {
                return ResourceManager.GetString("err_070600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_080100 {
            get {
                return ResourceManager.GetString("err_080100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号不存在 的本地化字符串。
        /// </summary>
        internal static string err_080200 {
            get {
                return ResourceManager.GetString("err_080200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名不能为空 的本地化字符串。
        /// </summary>
        internal static string err_080300 {
            get {
                return ResourceManager.GetString("err_080300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户编号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_080400 {
            get {
                return ResourceManager.GetString("err_080400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户编号不存在 的本地化字符串。
        /// </summary>
        internal static string err_080500 {
            get {
                return ResourceManager.GetString("err_080500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_080600 {
            get {
                return ResourceManager.GetString("err_080600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线路编号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_080700 {
            get {
                return ResourceManager.GetString("err_080700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线路编号不存在 的本地化字符串。
        /// </summary>
        internal static string err_080800 {
            get {
                return ResourceManager.GetString("err_080800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期不能为空 的本地化字符串。
        /// </summary>
        internal static string err_080900 {
            get {
                return ResourceManager.GetString("err_080900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期格式不正确 的本地化字符串。
        /// </summary>
        internal static string err_081000 {
            get {
                return ResourceManager.GetString("err_081000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期和线路编号不匹配 的本地化字符串。
        /// </summary>
        internal static string err_081100 {
            get {
                return ResourceManager.GetString("err_081100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访顺序格式不正确 的本地化字符串。
        /// </summary>
        internal static string err_081200 {
            get {
                return ResourceManager.GetString("err_081200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访频率不能为空 的本地化字符串。
        /// </summary>
        internal static string err_081300 {
            get {
                return ResourceManager.GetString("err_081300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访频率不存在 的本地化字符串。
        /// </summary>
        internal static string err_081400 {
            get {
                return ResourceManager.GetString("err_081400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不能为空 的本地化字符串。
        /// </summary>
        internal static string err_081500 {
            get {
                return ResourceManager.GetString("err_081500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不存在 的本地化字符串。
        /// </summary>
        internal static string err_081600 {
            get {
                return ResourceManager.GetString("err_081600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户的组织架构下不包含该客户 的本地化字符串。
        /// </summary>
        internal static string err_081700 {
            get {
                return ResourceManager.GetString("err_081700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访日期不能为空 的本地化字符串。
        /// </summary>
        internal static string err_090100 {
            get {
                return ResourceManager.GetString("err_090100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访日期格式不正确 的本地化字符串。
        /// </summary>
        internal static string err_090200 {
            get {
                return ResourceManager.GetString("err_090200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_090300 {
            get {
                return ResourceManager.GetString("err_090300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号不存在 的本地化字符串。
        /// </summary>
        internal static string err_090400 {
            get {
                return ResourceManager.GetString("err_090400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名不能为空 的本地化字符串。
        /// </summary>
        internal static string err_090500 {
            get {
                return ResourceManager.GetString("err_090500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户编号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_090600 {
            get {
                return ResourceManager.GetString("err_090600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户编号不存在 的本地化字符串。
        /// </summary>
        internal static string err_090700 {
            get {
                return ResourceManager.GetString("err_090700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_090800 {
            get {
                return ResourceManager.GetString("err_090800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不能为空 的本地化字符串。
        /// </summary>
        internal static string err_090900 {
            get {
                return ResourceManager.GetString("err_090900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不存在 的本地化字符串。
        /// </summary>
        internal static string err_091000 {
            get {
                return ResourceManager.GetString("err_091000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户的组织架构下不包含该客户 的本地化字符串。
        /// </summary>
        internal static string err_091100 {
            get {
                return ResourceManager.GetString("err_091100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访顺序不能为空 的本地化字符串。
        /// </summary>
        internal static string err_091200 {
            get {
                return ResourceManager.GetString("err_091200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访顺序格式不正确 的本地化字符串。
        /// </summary>
        internal static string err_091300 {
            get {
                return ResourceManager.GetString("err_091300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号不存在 的本地化字符串。
        /// </summary>
        internal static string err_100100 {
            get {
                return ResourceManager.GetString("err_100100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号不存在 的本地化字符串。
        /// </summary>
        internal static string err_100200 {
            get {
                return ResourceManager.GetString("err_100200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名不能为空 的本地化字符串。
        /// </summary>
        internal static string err_100300 {
            get {
                return ResourceManager.GetString("err_100300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户编号不能为空 的本地化字符串。
        /// </summary>
        internal static string err_100400 {
            get {
                return ResourceManager.GetString("err_100400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户编号不存在 的本地化字符串。
        /// </summary>
        internal static string err_100500 {
            get {
                return ResourceManager.GetString("err_100500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称不能为空 的本地化字符串。
        /// </summary>
        internal static string err_100600 {
            get {
                return ResourceManager.GetString("err_100600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不能为空 的本地化字符串。
        /// </summary>
        internal static string err_100700 {
            get {
                return ResourceManager.GetString("err_100700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不存在 的本地化字符串。
        /// </summary>
        internal static string err_100800 {
            get {
                return ResourceManager.GetString("err_100800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户的组织架构下不包含该客户 的本地化字符串。
        /// </summary>
        internal static string err_100900 {
            get {
                return ResourceManager.GetString("err_100900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户覆盖主数据错误信息 的本地化字符串。
        /// </summary>
        internal static string txt_CustomerCoverage {
            get {
                return ResourceManager.GetString("txt_CustomerCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户主数据错误信息 的本地化字符串。
        /// </summary>
        internal static string txt_CustomerError {
            get {
                return ResourceManager.GetString("txt_CustomerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载模板 的本地化字符串。
        /// </summary>
        internal static string txt_DownloadTemplate {
            get {
                return ResourceManager.GetString("txt_DownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您未安装FLASH控件 的本地化字符串。
        /// </summary>
        internal static string txt_FlashError {
            get {
                return ResourceManager.GetString("txt_FlashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品分销列表-客户主数据错误信息 的本地化字符串。
        /// </summary>
        internal static string txt_ProdListCustError {
            get {
                return ResourceManager.GetString("txt_ProdListCustError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品分销列表-产品主数据错误信息 的本地化字符串。
        /// </summary>
        internal static string txt_ProdListProdError {
            get {
                return ResourceManager.GetString("txt_ProdListProdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品主数据错误信息 的本地化字符串。
        /// </summary>
        internal static string txt_ProductError {
            get {
                return ResourceManager.GetString("txt_ProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必填， 的本地化字符串。
        /// </summary>
        internal static string txt_Require {
            get {
                return ResourceManager.GetString("txt_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访线路明细主数据错误信息 的本地化字符串。
        /// </summary>
        internal static string txt_RouteDetailError {
            get {
                return ResourceManager.GetString("txt_RouteDetailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访路线规划主数据错误信息 的本地化字符串。
        /// </summary>
        internal static string txt_RoutePlanError {
            get {
                return ResourceManager.GetString("txt_RoutePlanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择Excel工作簿（*.xlsx） 的本地化字符串。
        /// </summary>
        internal static string txt_selectExcel {
            get {
                return ResourceManager.GetString("txt_selectExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件 的本地化字符串。
        /// </summary>
        internal static string txt_SelectFile {
            get {
                return ResourceManager.GetString("txt_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤一: 准备数据文件 的本地化字符串。
        /// </summary>
        internal static string txt_Step1 {
            get {
                return ResourceManager.GetString("txt_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用数据模板文件录入信息。 的本地化字符串。
        /// </summary>
        internal static string txt_Step1Text1 {
            get {
                return ResourceManager.GetString("txt_Step1Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为保证正确导入，请按照模板内的要求进行填写 的本地化字符串。
        /// </summary>
        internal static string txt_Step1Text2 {
            get {
                return ResourceManager.GetString("txt_Step1Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤二: 上传数据文件 的本地化字符串。
        /// </summary>
        internal static string txt_Step2 {
            get {
                return ResourceManager.GetString("txt_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击下方按钮选择文件即可上传。目前仅支持Excel工作簿（*.xlsx）。 的本地化字符串。
        /// </summary>
        internal static string txt_Step2Text1 {
            get {
                return ResourceManager.GetString("txt_Step2Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板 的本地化字符串。
        /// </summary>
        internal static string txt_Template {
            get {
                return ResourceManager.GetString("txt_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以上为说明及范例,导入时不可删除!!! 的本地化字符串。
        /// </summary>
        internal static string txt_Tip {
            get {
                return ResourceManager.GetString("txt_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入数据失败 的本地化字符串。
        /// </summary>
        internal static string txt_UploadFailed {
            get {
                return ResourceManager.GetString("txt_UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户主数据错误信息 的本地化字符串。
        /// </summary>
        internal static string txt_UserError {
            get {
                return ResourceManager.GetString("txt_UserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户分销列表-产品主数据错误信息 的本地化字符串。
        /// </summary>
        internal static string txt_UserListProdError {
            get {
                return ResourceManager.GetString("txt_UserListProdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户分销列表-角色主数据错误信息 的本地化字符串。
        /// </summary>
        internal static string txt_UserListRoleError {
            get {
                return ResourceManager.GetString("txt_UserListRoleError", resourceCulture);
            }
        }
    }
}
