//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 每行代表一个选项，可以添加多个选项 的本地化字符串。
        /// </summary>
        internal static string msg_AddMultiOptions {
            get {
                return ResourceManager.GetString("msg_AddMultiOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父销售渠道已被客户引用，不应该允许添加子渠道 的本地化字符串。
        /// </summary>
        internal static string msg_AddSubChannelFail {
            get {
                return ResourceManager.GetString("msg_AddSubChannelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin Profile can not remove! 的本地化字符串。
        /// </summary>
        internal static string msg_AdminCanNotDelete {
            get {
                return ResourceManager.GetString("msg_AdminCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作提示 的本地化字符串。
        /// </summary>
        internal static string msg_AlertTitle {
            get {
                return ResourceManager.GetString("msg_AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认该组织架构下所有人员、客户、经销商都已转移 的本地化字符串。
        /// </summary>
        internal static string msg_AllTransfer {
            get {
                return ResourceManager.GetString("msg_AllTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认该销售渠道下所有人员、客户、经销商都已转移 的本地化字符串。
        /// </summary>
        internal static string msg_AllTransferChannel {
            get {
                return ResourceManager.GetString("msg_AllTransferChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要批量确认订单吗？ 的本地化字符串。
        /// </summary>
        internal static string msg_BatchConfirmOrder {
            get {
                return ResourceManager.GetString("msg_BatchConfirmOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要取消吗? 的本地化字符串。
        /// </summary>
        internal static string msg_CancelAlert {
            get {
                return ResourceManager.GetString("msg_CancelAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将取消所有 {0} 条记录，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string msg_CancelAllRecord {
            get {
                return ResourceManager.GetString("msg_CancelAllRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要取消订单吗？ 的本地化字符串。
        /// </summary>
        internal static string msg_CancelOrder {
            get {
                return ResourceManager.GetString("msg_CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售渠道不能为空 的本地化字符串。
        /// </summary>
        internal static string msg_ChannelRequired {
            get {
                return ResourceManager.GetString("msg_ChannelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左侧无可关闭选项 的本地化字符串。
        /// </summary>
        internal static string msg_CloseLeft {
            get {
                return ResourceManager.GetString("msg_CloseLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右侧无可关闭选项 的本地化字符串。
        /// </summary>
        internal static string msg_CloseRight {
            get {
                return ResourceManager.GetString("msg_CloseRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要取消订单吗？ 的本地化字符串。
        /// </summary>
        internal static string msg_ConfirmCancelOrder {
            get {
                return ResourceManager.GetString("msg_ConfirmCancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        internal static string msg_ConnectionFailed {
            get {
                return ResourceManager.GetString("msg_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此客户一经审核通过则进入客户维护模块，请确认！ 的本地化字符串。
        /// </summary>
        internal static string msg_CustomerApproval {
            get {
                return ResourceManager.GetString("msg_CustomerApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户不存在 的本地化字符串。
        /// </summary>
        internal static string msg_CustomerNotExist {
            get {
                return ResourceManager.GetString("msg_CustomerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称已存在 的本地化字符串。
        /// </summary>
        internal static string msg_CustProdListNameExist {
            get {
                return ResourceManager.GetString("msg_CustProdListNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入完整的拜访信息 的本地化字符串。
        /// </summary>
        internal static string msg_DataRequired {
            get {
                return ResourceManager.GetString("msg_DataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择日期 的本地化字符串。
        /// </summary>
        internal static string msg_DateRequired {
            get {
                return ResourceManager.GetString("msg_DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除后将不能恢复，您真的要删除吗? 的本地化字符串。
        /// </summary>
        internal static string msg_DeleteAlert {
            get {
                return ResourceManager.GetString("msg_DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除拜访流程后相关的任务和明细也将会被删除，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string msg_DeleteVisitProcess {
            get {
                return ResourceManager.GetString("msg_DeleteVisitProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除任务后里面的明细也将被删除，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string msg_DeleteVisitTask {
            get {
                return ResourceManager.GetString("msg_DeleteVisitTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货日期不能小于订单日期 的本地化字符串。
        /// </summary>
        internal static string msg_DeliveryDateOrderDate {
            get {
                return ResourceManager.GetString("msg_DeliveryDateOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门名称已存在 的本地化字符串。
        /// </summary>
        internal static string msg_DepartmentNameExist {
            get {
                return ResourceManager.GetString("msg_DepartmentNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司代码不能为空 的本地化字符串。
        /// </summary>
        internal static string msg_DomainRequired {
            get {
                return ResourceManager.GetString("msg_DomainRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间不能为空 的本地化字符串。
        /// </summary>
        internal static string msg_EndDateRequired {
            get {
                return ResourceManager.GetString("msg_EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已生效的问卷不能编辑，会影响到手机端上传的问卷结果 的本地化字符串。
        /// </summary>
        internal static string msg_ExecutedSurveyNotModify {
            get {
                return ResourceManager.GetString("msg_ExecutedSurveyNotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经销商已存在 的本地化字符串。
        /// </summary>
        internal static string msg_ExistDistributor {
            get {
                return ResourceManager.GetString("msg_ExistDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在相同的编号 的本地化字符串。
        /// </summary>
        internal static string msg_ExistSameCode {
            get {
                return ResourceManager.GetString("msg_ExistSameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在相同的账号 的本地化字符串。
        /// </summary>
        internal static string msg_ExistSameID {
            get {
                return ResourceManager.GetString("msg_ExistSameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在相同的采集项 的本地化字符串。
        /// </summary>
        internal static string msg_ExistSameItem {
            get {
                return ResourceManager.GetString("msg_ExistSameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在相同的任务 的本地化字符串。
        /// </summary>
        internal static string msg_ExistSameTask {
            get {
                return ResourceManager.GetString("msg_ExistSameTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挂接客户失败 的本地化字符串。
        /// </summary>
        internal static string msg_FailedCustomer {
            get {
                return ResourceManager.GetString("msg_FailedCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挂接负责人失败 的本地化字符串。
        /// </summary>
        internal static string msg_FailedUser {
            get {
                return ResourceManager.GetString("msg_FailedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择费用类型 的本地化字符串。
        /// </summary>
        internal static string msg_FeeTypeRequired {
            get {
                return ResourceManager.GetString("msg_FeeTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入完整数据 的本地化字符串。
        /// </summary>
        internal static string msg_FillBlankDate {
            get {
                return ResourceManager.GetString("msg_FillBlankDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入订单明细 的本地化字符串。
        /// </summary>
        internal static string msg_FillOrderDetail {
            get {
                return ResourceManager.GetString("msg_FillOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访频率不能为空 的本地化字符串。
        /// </summary>
        internal static string msg_FrequencyRequired {
            get {
                return ResourceManager.GetString("msg_FrequencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据已经被删除 的本地化字符串。
        /// </summary>
        internal static string msg_HasbeenDeleted {
            get {
                return ResourceManager.GetString("msg_HasbeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入新流程名称 的本地化字符串。
        /// </summary>
        internal static string msg_InputNewProcessName {
            get {
                return ResourceManager.GetString("msg_InputNewProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入新任务名称 的本地化字符串。
        /// </summary>
        internal static string msg_InputNewTaskName {
            get {
                return ResourceManager.GetString("msg_InputNewTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本不允许为空 的本地化字符串。
        /// </summary>
        internal static string msg_IsNull {
            get {
                return ResourceManager.GetString("msg_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败: 用户名或密码错误 的本地化字符串。
        /// </summary>
        internal static string msg_LoginFailed {
            get {
                return ResourceManager.GetString("msg_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已被禁用 的本地化字符串。
        /// </summary>
        internal static string msg_LoginLocked {
            get {
                return ResourceManager.GetString("msg_LoginLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        internal static string msg_LoginNameRequired {
            get {
                return ResourceManager.GetString("msg_LoginNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录已超时，请重新登录 的本地化字符串。
        /// </summary>
        internal static string msg_LoginTimeout {
            get {
                return ResourceManager.GetString("msg_LoginTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要注销吗? 的本地化字符串。
        /// </summary>
        internal static string msg_LogOut {
            get {
                return ResourceManager.GetString("msg_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发表评论成功 的本地化字符串。
        /// </summary>
        internal static string msg_MakeCommentSuccessed {
            get {
                return ResourceManager.GetString("msg_MakeCommentSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码为空 的本地化字符串。
        /// </summary>
        internal static string msg_MobileEmpty {
            get {
                return ResourceManager.GetString("msg_MobileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码已经被其它登录帐号使用 的本地化字符串。
        /// </summary>
        internal static string msg_MobileUsedOtherAccount {
            get {
                return ResourceManager.GetString("msg_MobileUsedOtherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单数量没有被修改 的本地化字符串。
        /// </summary>
        internal static string msg_ModifyOrderQty {
            get {
                return ResourceManager.GetString("msg_ModifyOrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择月份 的本地化字符串。
        /// </summary>
        internal static string msg_MonthRequired {
            get {
                return ResourceManager.GetString("msg_MonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能重复 的本地化字符串。
        /// </summary>
        internal static string msg_NameExisted {
            get {
                return ResourceManager.GetString("msg_NameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能为空 的本地化字符串。
        /// </summary>
        internal static string msg_NameRequired {
            get {
                return ResourceManager.GetString("msg_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不允许为空 的本地化字符串。
        /// </summary>
        internal static string msg_NewPasswordRequired {
            get {
                return ResourceManager.GetString("msg_NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无数据 的本地化字符串。
        /// </summary>
        internal static string msg_NoData {
            get {
                return ResourceManager.GetString("msg_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User has no role 的本地化字符串。
        /// </summary>
        internal static string msg_NoRole {
            get {
                return ResourceManager.GetString("msg_NoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂不支持 的本地化字符串。
        /// </summary>
        internal static string msg_NoSupport {
            get {
                return ResourceManager.GetString("msg_NoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下订单的流程不能创建任务 的本地化字符串。
        /// </summary>
        internal static string msg_NotVisitTaskInOrdre {
            get {
                return ResourceManager.GetString("msg_NotVisitTaskInOrdre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原密码错误 的本地化字符串。
        /// </summary>
        internal static string msg_OldPasswordError {
            get {
                return ResourceManager.GetString("msg_OldPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访流程里面只能有一个下订单的流程 的本地化字符串。
        /// </summary>
        internal static string msg_OneOrderInTaskProcess {
            get {
                return ResourceManager.GetString("msg_OneOrderInTaskProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单已经被更改 的本地化字符串。
        /// </summary>
        internal static string msg_OrderEdited {
            get {
                return ResourceManager.GetString("msg_OrderEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单提交成功 的本地化字符串。
        /// </summary>
        internal static string msg_OrderSaveSuccess {
            get {
                return ResourceManager.GetString("msg_OrderSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级组织名称不允许和组织名称相同 的本地化字符串。
        /// </summary>
        internal static string msg_Organization {
            get {
                return ResourceManager.GetString("msg_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择组织架构 的本地化字符串。
        /// </summary>
        internal static string msg_OrganizationRequired {
            get {
                return ResourceManager.GetString("msg_OrganizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select an organization. 的本地化字符串。
        /// </summary>
        internal static string msg_OrgRequired {
            get {
                return ResourceManager.GetString("msg_OrgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string msg_PasswordRequired {
            get {
                return ResourceManager.GetString("msg_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码由6-10个字符组成，至少包括数字和小写字母 的本地化字符串。
        /// </summary>
        internal static string msg_PasswordStrong {
            get {
                return ResourceManager.GetString("msg_PasswordStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择付款方式 的本地化字符串。
        /// </summary>
        internal static string msg_PaymentTypeRequired {
            get {
                return ResourceManager.GetString("msg_PaymentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品不能重复 的本地化字符串。
        /// </summary>
        internal static string msg_ProductDupliacte {
            get {
                return ResourceManager.GetString("msg_ProductDupliacte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码和确认密码不一致 的本地化字符串。
        /// </summary>
        internal static string msg_PwdConsistent {
            get {
                return ResourceManager.GetString("msg_PwdConsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置密码成功 的本地化字符串。
        /// </summary>
        internal static string msg_ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("msg_ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色已存在 的本地化字符串。
        /// </summary>
        internal static string msg_RoleExist {
            get {
                return ResourceManager.GetString("msg_RoleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择角色 的本地化字符串。
        /// </summary>
        internal static string msg_RoleRequired {
            get {
                return ResourceManager.GetString("msg_RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入销售费用 的本地化字符串。
        /// </summary>
        internal static string msg_SalesFeeRequired {
            get {
                return ResourceManager.GetString("msg_SalesFeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择业务代表 的本地化字符串。
        /// </summary>
        internal static string msg_SalesRepRequired {
            get {
                return ResourceManager.GetString("msg_SalesRepRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访流程名字不能重复 的本地化字符串。
        /// </summary>
        internal static string msg_SameProcessInVisitTask {
            get {
                return ResourceManager.GetString("msg_SameProcessInVisitTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访模板名字不能重复 的本地化字符串。
        /// </summary>
        internal static string msg_SameSettingInVisitTask {
            get {
                return ResourceManager.GetString("msg_SameSettingInVisitTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访任务名称不能重复 的本地化字符串。
        /// </summary>
        internal static string msg_SameTaskInVisitTask {
            get {
                return ResourceManager.GetString("msg_SameTaskInVisitTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string msg_SaveFailed {
            get {
                return ResourceManager.GetString("msg_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将保存所有已选择 {0} 条记录，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string msg_SaveSelectedRecord {
            get {
                return ResourceManager.GetString("msg_SaveSelectedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选中需要新增的文本 的本地化字符串。
        /// </summary>
        internal static string msg_SelAdd {
            get {
                return ResourceManager.GetString("msg_SelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择客户 的本地化字符串。
        /// </summary>
        internal static string msg_SelectCustomer {
            get {
                return ResourceManager.GetString("msg_SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择维度 的本地化字符串。
        /// </summary>
        internal static string msg_SelectDimension {
            get {
                return ResourceManager.GetString("msg_SelectDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择节点销售渠道 的本地化字符串。
        /// </summary>
        internal static string msg_SelectNodeChannel {
            get {
                return ResourceManager.GetString("msg_SelectNodeChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择父部门 的本地化字符串。
        /// </summary>
        internal static string msg_SelectParentDepartment {
            get {
                return ResourceManager.GetString("msg_SelectParentDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择照片类型 的本地化字符串。
        /// </summary>
        internal static string msg_SelectPhotoType {
            get {
                return ResourceManager.GetString("msg_SelectPhotoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一条记录 的本地化字符串。
        /// </summary>
        internal static string msg_SelectRecord {
            get {
                return ResourceManager.GetString("msg_SelectRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择角色 的本地化字符串。
        /// </summary>
        internal static string msg_SelectRole {
            get {
                return ResourceManager.GetString("msg_SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择分销列表 的本地化字符串。
        /// </summary>
        internal static string msg_SelectSalesList {
            get {
                return ResourceManager.GetString("msg_SelectSalesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择问卷组 的本地化字符串。
        /// </summary>
        internal static string msg_SelectSurveyGroup {
            get {
                return ResourceManager.GetString("msg_SelectSurveyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择任务组 的本地化字符串。
        /// </summary>
        internal static string msg_SelectTaskGroup {
            get {
                return ResourceManager.GetString("msg_SelectTaskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择移交的业务范围 的本地化字符串。
        /// </summary>
        internal static string msg_SelectTransferScope {
            get {
                return ResourceManager.GetString("msg_SelectTransferScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择上传间隔 的本地化字符串。
        /// </summary>
        internal static string msg_SelectUploadInterval {
            get {
                return ResourceManager.GetString("msg_SelectUploadInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择用户 的本地化字符串。
        /// </summary>
        internal static string msg_SelectUser {
            get {
                return ResourceManager.GetString("msg_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择有效的父渠道 的本地化字符串。
        /// </summary>
        internal static string msg_SelectValidParentChannel {
            get {
                return ResourceManager.GetString("msg_SelectValidParentChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择有效的父部门 的本地化字符串。
        /// </summary>
        internal static string msg_SelectValidParentDepartment {
            get {
                return ResourceManager.GetString("msg_SelectValidParentDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选中需要修改的文本 的本地化字符串。
        /// </summary>
        internal static string msg_SelUpdate {
            get {
                return ResourceManager.GetString("msg_SelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访顺序不能为空 的本地化字符串。
        /// </summary>
        internal static string msg_SequenceRequired {
            get {
                return ResourceManager.GetString("msg_SequenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The shipment can&apos;t be reassign 的本地化字符串。
        /// </summary>
        internal static string msg_ShipmentCannotReassign {
            get {
                return ResourceManager.GetString("msg_ShipmentCannotReassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *为必填项 的本地化字符串。
        /// </summary>
        internal static string msg_StarRequired {
            get {
                return ResourceManager.GetString("msg_StarRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期不能小于今天 的本地化字符串。
        /// </summary>
        internal static string msg_StartDateNotLessToday {
            get {
                return ResourceManager.GetString("msg_StartDateNotLessToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期不能为空 的本地化字符串。
        /// </summary>
        internal static string msg_StartDateRequired {
            get {
                return ResourceManager.GetString("msg_StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间不能小于开始时间 的本地化字符串。
        /// </summary>
        internal static string msg_StartTimeEndTime {
            get {
                return ResourceManager.GetString("msg_StartTimeEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string msg_Succeed {
            get {
                return ResourceManager.GetString("msg_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要重置密码吗？ 的本地化字符串。
        /// </summary>
        internal static string msg_SureResetPassword {
            get {
                return ResourceManager.GetString("msg_SureResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板错误，请重新下载模板 的本地化字符串。
        /// </summary>
        internal static string msg_TemplateError {
            get {
                return ResourceManager.GetString("msg_TemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温馨提示 的本地化字符串。
        /// </summary>
        internal static string msg_topTitle {
            get {
                return ResourceManager.GetString("msg_topTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前选中的文本不允许被修改 的本地化字符串。
        /// </summary>
        internal static string msg_Update {
            get {
                return ResourceManager.GetString("msg_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误，亲 的本地化字符串。
        /// </summary>
        internal static string msg_ValidateCodeError {
            get {
                return ResourceManager.GetString("msg_ValidateCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码不能为空 的本地化字符串。
        /// </summary>
        internal static string msg_ValidateCodeRequired {
            get {
                return ResourceManager.GetString("msg_ValidateCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核不通过的客户只在此模块保留3天，3天后将删除客户信息，请确认！ 的本地化字符串。
        /// </summary>
        internal static string msg_VerifyMessage {
            get {
                return ResourceManager.GetString("msg_VerifyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访日期不能小于今天 的本地化字符串。
        /// </summary>
        internal static string msg_VisitDateNotLessToday {
            get {
                return ResourceManager.GetString("msg_VisitDateNotLessToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前客户拜访顺序已存在重复值 的本地化字符串。
        /// </summary>
        internal static string msg_VisitSequenceDuplicateValues {
            get {
                return ResourceManager.GetString("msg_VisitSequenceDuplicateValues", resourceCulture);
            }
        }
    }
}
