//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Module {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Module() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Module", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 考勤 的本地化字符串。
        /// </summary>
        internal static string Menu_Attendance {
            get {
                return ResourceManager.GetString("Menu_Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤配置 的本地化字符串。
        /// </summary>
        internal static string Menu_AttendanceSetting {
            get {
                return ResourceManager.GetString("Menu_AttendanceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤轨迹 的本地化字符串。
        /// </summary>
        internal static string Menu_AttendanceView {
            get {
                return ResourceManager.GetString("Menu_AttendanceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统权限 的本地化字符串。
        /// </summary>
        internal static string Menu_Authorization {
            get {
                return ResourceManager.GetString("Menu_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售渠道 的本地化字符串。
        /// </summary>
        internal static string Menu_Channel {
            get {
                return ResourceManager.GetString("Menu_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统列表 的本地化字符串。
        /// </summary>
        internal static string Menu_Configuration {
            get {
                return ResourceManager.GetString("Menu_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户维护 的本地化字符串。
        /// </summary>
        internal static string Menu_Customer {
            get {
                return ResourceManager.GetString("Menu_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新客户审核 的本地化字符串。
        /// </summary>
        internal static string Menu_CustomerAudit {
            get {
                return ResourceManager.GetString("Menu_CustomerAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户覆盖(按业代) 的本地化字符串。
        /// </summary>
        internal static string Menu_CustomerCoverage {
            get {
                return ResourceManager.GetString("Menu_CustomerCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门维护 的本地化字符串。
        /// </summary>
        internal static string Menu_Department {
            get {
                return ResourceManager.GetString("Menu_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经销商管理 的本地化字符串。
        /// </summary>
        internal static string Menu_Distributor {
            get {
                return ResourceManager.GetString("Menu_Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机报表 的本地化字符串。
        /// </summary>
        internal static string Menu_MobileReporting {
            get {
                return ResourceManager.GetString("Menu_MobileReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售记录 的本地化字符串。
        /// </summary>
        internal static string Menu_OrderConfirm {
            get {
                return ResourceManager.GetString("Menu_OrderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单查询 的本地化字符串。
        /// </summary>
        internal static string Menu_OrderView {
            get {
                return ResourceManager.GetString("Menu_OrderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织架构 的本地化字符串。
        /// </summary>
        internal static string Menu_Organization {
            get {
                return ResourceManager.GetString("Menu_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照上传 的本地化字符串。
        /// </summary>
        internal static string Menu_Photo {
            get {
                return ResourceManager.GetString("Menu_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片查看 的本地化字符串。
        /// </summary>
        internal static string Menu_PhotoView {
            get {
                return ResourceManager.GetString("Menu_PhotoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下订单 的本地化字符串。
        /// </summary>
        internal static string Menu_PlaceOrder {
            get {
                return ResourceManager.GetString("Menu_PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品管理 的本地化字符串。
        /// </summary>
        internal static string Menu_Product {
            get {
                return ResourceManager.GetString("Menu_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品属性维护 的本地化字符串。
        /// </summary>
        internal static string Menu_ProductAttribute {
            get {
                return ResourceManager.GetString("Menu_ProductAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品列表(按客户) 的本地化字符串。
        /// </summary>
        internal static string Menu_ProductCustSalesList {
            get {
                return ResourceManager.GetString("Menu_ProductCustSalesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品列表(按业代) 的本地化字符串。
        /// </summary>
        internal static string Menu_ProductUserSalesList {
            get {
                return ResourceManager.GetString("Menu_ProductUserSalesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访计划 的本地化字符串。
        /// </summary>
        internal static string Menu_RouteDetail {
            get {
                return ResourceManager.GetString("Menu_RouteDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访规则配置 的本地化字符串。
        /// </summary>
        internal static string Menu_RoutePlan {
            get {
                return ResourceManager.GetString("Menu_RoutePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售单 的本地化字符串。
        /// </summary>
        internal static string Menu_SalesOrder {
            get {
                return ResourceManager.GetString("Menu_SalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业代报表 的本地化字符串。
        /// </summary>
        internal static string Menu_SalesReport {
            get {
                return ResourceManager.GetString("Menu_SalesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户销量报表 的本地化字符串。
        /// </summary>
        internal static string Menu_SalesReportByCust {
            get {
                return ResourceManager.GetString("Menu_SalesReportByCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销量报表 的本地化字符串。
        /// </summary>
        internal static string Menu_SalesVolumeReport {
            get {
                return ResourceManager.GetString("Menu_SalesVolumeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷执行 的本地化字符串。
        /// </summary>
        internal static string Menu_SurveyExecution {
            get {
                return ResourceManager.GetString("Menu_SurveyExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷配置 的本地化字符串。
        /// </summary>
        internal static string Menu_SurveySetting {
            get {
                return ResourceManager.GetString("Menu_SurveySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷查看 的本地化字符串。
        /// </summary>
        internal static string Menu_SurveyView {
            get {
                return ResourceManager.GetString("Menu_SurveyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务分配 的本地化字符串。
        /// </summary>
        internal static string Menu_TaskAssignment {
            get {
                return ResourceManager.GetString("Menu_TaskAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务执行 的本地化字符串。
        /// </summary>
        internal static string Menu_TaskExecution {
            get {
                return ResourceManager.GetString("Menu_TaskExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务查看 的本地化字符串。
        /// </summary>
        internal static string Menu_TaskView {
            get {
                return ResourceManager.GetString("Menu_TaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员管理 的本地化字符串。
        /// </summary>
        internal static string Menu_User {
            get {
                return ResourceManager.GetString("Menu_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组 的本地化字符串。
        /// </summary>
        internal static string Menu_UserGroup {
            get {
                return ResourceManager.GetString("Menu_UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户拜访 的本地化字符串。
        /// </summary>
        internal static string Menu_Visit {
            get {
                return ResourceManager.GetString("Menu_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访达成报表 的本地化字符串。
        /// </summary>
        internal static string Menu_VisitRateReport {
            get {
                return ResourceManager.GetString("Menu_VisitRateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访日志 的本地化字符串。
        /// </summary>
        internal static string Menu_VisitResult {
            get {
                return ResourceManager.GetString("Menu_VisitResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访流程配置 的本地化字符串。
        /// </summary>
        internal static string Menu_VisitTask {
            get {
                return ResourceManager.GetString("Menu_VisitTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拜访轨迹 的本地化字符串。
        /// </summary>
        internal static string Menu_VisitTracking {
            get {
                return ResourceManager.GetString("Menu_VisitTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员考勤 的本地化字符串。
        /// </summary>
        internal static string Module_Attendance {
            get {
                return ResourceManager.GetString("Module_Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础资料 的本地化字符串。
        /// </summary>
        internal static string Module_Customer {
            get {
                return ResourceManager.GetString("Module_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机报表 的本地化字符串。
        /// </summary>
        internal static string Module_MobileReporting {
            get {
                return ResourceManager.GetString("Module_MobileReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售管理 的本地化字符串。
        /// </summary>
        internal static string Module_Order {
            get {
                return ResourceManager.GetString("Module_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照上传 的本地化字符串。
        /// </summary>
        internal static string Module_Photo {
            get {
                return ResourceManager.GetString("Module_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片查看 的本地化字符串。
        /// </summary>
        internal static string Module_PhotoView {
            get {
                return ResourceManager.GetString("Module_PhotoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下订单 的本地化字符串。
        /// </summary>
        internal static string Module_PlaceOrder {
            get {
                return ResourceManager.GetString("Module_PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅助资料 的本地化字符串。
        /// </summary>
        internal static string Module_Product {
            get {
                return ResourceManager.GetString("Module_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务配置 的本地化字符串。
        /// </summary>
        internal static string Module_Reporting {
            get {
                return ResourceManager.GetString("Module_Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表查看 的本地化字符串。
        /// </summary>
        internal static string Module_ReportView {
            get {
                return ResourceManager.GetString("Module_ReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调查问卷 的本地化字符串。
        /// </summary>
        internal static string Module_Survey {
            get {
                return ResourceManager.GetString("Module_Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统配置 的本地化字符串。
        /// </summary>
        internal static string Module_System {
            get {
                return ResourceManager.GetString("Module_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主管任务 的本地化字符串。
        /// </summary>
        internal static string Module_Task {
            get {
                return ResourceManager.GetString("Module_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员管理 的本地化字符串。
        /// </summary>
        internal static string Module_User {
            get {
                return ResourceManager.GetString("Module_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户拜访 的本地化字符串。
        /// </summary>
        internal static string Module_Visit {
            get {
                return ResourceManager.GetString("Module_Visit", resourceCulture);
            }
        }
    }
}
