//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_T_ShipmentHeader
    {
        public DSD_T_ShipmentHeader()
        {
            this.DSD_T_ShipmentFinance = new HashSet<DSD_T_ShipmentFinance>();
            this.DSD_T_ShipmentItem = new HashSet<DSD_T_ShipmentItem>();
        }
    
        public System.Guid Id { get; set; }
        public string ShipmentNo { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public string ActionType { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Odometer { get; set; }
        public string Checker { get; set; }
        public Nullable<int> CheckerConfirm { get; set; }
        public Nullable<System.DateTime> CheckerConfirmTime { get; set; }
        public string CheckerSignImg { get; set; }
        public string DCheckerSignImg { get; set; }
        public string Cashier { get; set; }
        public Nullable<int> CashierConfirm { get; set; }
        public Nullable<System.DateTime> CashierConfirmTime { get; set; }
        public string CashierSignImg { get; set; }
        public string DCashierSignImg { get; set; }
        public string Gatekeeper { get; set; }
        public Nullable<int> GKConfirm { get; set; }
        public Nullable<System.DateTime> GKConfirmTime { get; set; }
        public string GKSignImg { get; set; }
        public string DGKSignImg { get; set; }
        public string WarehouseCode { get; set; }
        public string Status { get; set; }
        public string Driver { get; set; }
        public Nullable<int> TruckId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<decimal> WeightUnit { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual DSD_M_ShipmentHeader DSD_M_ShipmentHeader { get; set; }
        public virtual ICollection<DSD_T_ShipmentFinance> DSD_T_ShipmentFinance { get; set; }
        public virtual MD_Warehouse MD_Warehouse { get; set; }
        public virtual MD_User MD_User { get; set; }
        public virtual ICollection<DSD_T_ShipmentItem> DSD_T_ShipmentItem { get; set; }
    }
}
