//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_M_OrgSystemConfig
    {
        public int ID { get; set; }
        public int SystemConfigID { get; set; }
        public int OrgID { get; set; }
        public string Value { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Valid { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual DSD_M_SystemConfig DSD_M_SystemConfig { get; set; }
        public virtual MD_Organization MD_Organization { get; set; }
    }
}
