//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_T_TruckStock
    {
        public int TruckId { get; set; }
        public string ShipmentNo { get; set; }
        public string ProductCode { get; set; }
        public string ProductUnit { get; set; }
        public Nullable<int> StockQty { get; set; }
        public Nullable<int> SaleableQty { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual DSD_M_Truck DSD_M_Truck { get; set; }
        public virtual MD_Product MD_Product { get; set; }
    }
}
