//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_T_DayTimeTracking
    {
        public DSD_T_DayTimeTracking()
        {
            this.DSD_T_TruckCheckResult = new HashSet<DSD_T_TruckCheckResult>();
        }
    
        public System.Guid ID { get; set; }
        public System.DateTime WorkDate { get; set; }
        public string UserCode { get; set; }
        public int TruckId { get; set; }
        public System.DateTime TrackingTime { get; set; }
        public string TrackingType { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<bool> Signature { get; set; }
        public string SignImg { get; set; }
        public Nullable<int> Odometer { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual DSD_M_Truck DSD_M_Truck { get; set; }
        public virtual MD_User MD_User { get; set; }
        public virtual ICollection<DSD_T_TruckCheckResult> DSD_T_TruckCheckResult { get; set; }
    }
}
