//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_T_ShipmentItem
    {
        public System.Guid HeaderId { get; set; }
        public string ProductCode { get; set; }
        public string ProductUnit { get; set; }
        public Nullable<int> PlanQty { get; set; }
        public Nullable<int> ActualQty { get; set; }
        public Nullable<int> DifferenceQty { get; set; }
        public string DifferenceReason { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual DSD_T_ShipmentHeader DSD_T_ShipmentHeader { get; set; }
    }
}
