//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_M_DeliveryHeader
    {
        public DSD_M_DeliveryHeader()
        {
            this.DSD_M_DeliveryItem = new HashSet<DSD_M_DeliveryItem>();
            this.DSD_T_Invoice = new HashSet<DSD_T_Invoice>();
        }
    
        public string DeliveryNo { get; set; }
        public string ShipmentNo { get; set; }
        public string DeliveryType { get; set; }
        public string DeliveryStatus { get; set; }
        public string AccountNumber { get; set; }
        public string OrderNo { get; set; }
        public string InvoiceNo { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> PlanDeliveryDate { get; set; }
        public string SalesRep { get; set; }
        public string CompanyCode { get; set; }
        public string SalesOrg { get; set; }
        public string SalesOff { get; set; }
        public string PaymentType { get; set; }
        public string Currency { get; set; }
        public string PlanDeliveryQty { get; set; }
        public string DeliveryAddress { get; set; }
        public string Contact { get; set; }
        public string Telephone { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string DataSource { get; set; }
        public string DeliveryNote { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual ICollection<DSD_M_DeliveryItem> DSD_M_DeliveryItem { get; set; }
        public virtual DSD_M_ShipmentHeader DSD_M_ShipmentHeader { get; set; }
        public virtual MD_Account MD_Account { get; set; }
        public virtual ICollection<DSD_T_Invoice> DSD_T_Invoice { get; set; }
    }
}
