//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_T_ARCollection
    {
        public DSD_T_ARCollection()
        {
            this.DSD_T_ARInvoice = new HashSet<DSD_T_ARInvoice>();
            this.DSD_T_Payment = new HashSet<DSD_T_Payment>();
        }
    
        public string ID { get; set; }
        public string ebMobile__Account__c { get; set; }
        public Nullable<bool> ebMobile__IsActive__c { get; set; }
        public Nullable<decimal> ebMobile__CollectedAmount__c { get; set; }
        public Nullable<System.DateTime> ebMobile__CollectionDate__c { get; set; }
        public string ebMobile__GUID__c { get; set; }
        public Nullable<decimal> ebMobile__OffsetNumber__c { get; set; }
        public Nullable<decimal> ebMobile__OpenBalance__c { get; set; }
        public string ebMobile__ReceiptNumber__c { get; set; }
        public Nullable<decimal> ebMobile__RecordAction__c { get; set; }
        public string ebMobile__VisitID__c { get; set; }
        public string InvoiceStatus { get; set; }
        public Nullable<bool> CustomerSignStatus { get; set; }
        public Nullable<System.DateTime> CustomerSignDate { get; set; }
        public string CustomerSignImg { get; set; }
        public Nullable<bool> DriverSignStatus { get; set; }
        public Nullable<System.DateTime> DriverSignDate { get; set; }
        public string DriverSignImg { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual ICollection<DSD_T_ARInvoice> DSD_T_ARInvoice { get; set; }
        public virtual ICollection<DSD_T_Payment> DSD_T_Payment { get; set; }
    }
}
