//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_M_Truck
    {
        public DSD_M_Truck()
        {
            this.DSD_T_DayTimeTracking = new HashSet<DSD_T_DayTimeTracking>();
            this.DSD_T_ShipmentAssign = new HashSet<DSD_T_ShipmentAssign>();
            this.DSD_T_TruckStockTracking = new HashSet<DSD_T_TruckStockTracking>();
            this.DSD_T_TruckStock = new HashSet<DSD_T_TruckStock>();
        }
    
        public int ID { get; set; }
        public string TruckCode { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string VolumeUnit { get; set; }
        public string CompanyCode { get; set; }
        public string SalesOrg { get; set; }
        public string SalesOff { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
    
        public virtual ICollection<DSD_T_DayTimeTracking> DSD_T_DayTimeTracking { get; set; }
        public virtual ICollection<DSD_T_ShipmentAssign> DSD_T_ShipmentAssign { get; set; }
        public virtual ICollection<DSD_T_TruckStockTracking> DSD_T_TruckStockTracking { get; set; }
        public virtual ICollection<DSD_T_TruckStock> DSD_T_TruckStock { get; set; }
    }
}
