//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_M_TruckCheckList
    {
        public DSD_M_TruckCheckList()
        {
            this.DSD_M_TruckCheckAssign = new HashSet<DSD_M_TruckCheckAssign>();
            this.DSD_T_TruckCheckResult = new HashSet<DSD_T_TruckCheckResult>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CheckListId { get; set; }
        public int ParentId { get; set; }
        public string Content { get; set; }
        public int Level { get; set; }
        public string InputType { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> MustToDo { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool Valid { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual ICollection<DSD_M_TruckCheckAssign> DSD_M_TruckCheckAssign { get; set; }
        public virtual ICollection<DSD_T_TruckCheckResult> DSD_T_TruckCheckResult { get; set; }
    }
}
