//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_T_DeliveryHeader
    {
        public string DeliveryNo { get; set; }
        public string VisitId { get; set; }
        public string ShipmentNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryType { get; set; }
        public string DeliveryStatus { get; set; }
        public string AccountNumber { get; set; }
        public string OrderNo { get; set; }
        public string InvoiceNo { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> CustomerSignStatus { get; set; }
        public Nullable<System.DateTime> CustomerSignDate { get; set; }
        public string CustomerSignImg { get; set; }
        public Nullable<bool> DriverSignStatus { get; set; }
        public Nullable<System.DateTime> DriverSignDate { get; set; }
        public string DriverSignImg { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> ActualPayment { get; set; }
        public Nullable<decimal> ActualDeposit { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public string CancelReason { get; set; }
        public string DeliveryNote { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string Rebook { get; set; }
    
        public virtual DSD_M_ShipmentHeader DSD_M_ShipmentHeader { get; set; }
        public virtual MD_Account MD_Account { get; set; }
        public virtual DSD_T_Visit DSD_T_Visit { get; set; }
    }
}
