//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_M_DeliveryItem
    {
        public string DeliveryNo { get; set; }
        public string ProductCode { get; set; }
        public string ProductUnit { get; set; }
        public Nullable<int> PlanQty { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual DSD_M_DeliveryHeader DSD_M_DeliveryHeader { get; set; }
        public virtual MD_Product MD_Product { get; set; }
    }
}
