//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_M_SystemConfig
    {
        public DSD_M_SystemConfig()
        {
            this.DSD_M_OrgSystemConfig = new HashSet<DSD_M_OrgSystemConfig>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
        public string KeyName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual ICollection<DSD_M_OrgSystemConfig> DSD_M_OrgSystemConfig { get; set; }
    }
}
