//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_T_Invoice
    {
        public DSD_T_Invoice()
        {
            this.DSD_T_InvoiceItem = new HashSet<DSD_T_InvoiceItem>();
        }
    
        public string InvoiceNo { get; set; }
        public string DelliveryNo { get; set; }
        public string ShipmentNo { get; set; }
        public string CompanCode { get; set; }
        public string WarehouseCode { get; set; }
        public string OrderNo { get; set; }
        public string BSTKD { get; set; }
        public string OrderComment { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string SalesOff { get; set; }
        public string PaymentType { get; set; }
        public string PaymentTerm { get; set; }
        public string InvoiceInTimeFlag { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string AGCUST { get; set; }
        public string RECUST { get; set; }
        public string RGCUST { get; set; }
        public string WECUST { get; set; }
        public string SalesRep { get; set; }
        public Nullable<decimal> SAPReceivable { get; set; }
        public Nullable<decimal> SAPReceivalbeDeposit { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> DepositPrice { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> DSDReceivableDeposit { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<decimal> ActualDeposit { get; set; }
        public string Remark { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual DSD_M_DeliveryHeader DSD_M_DeliveryHeader { get; set; }
        public virtual ICollection<DSD_T_InvoiceItem> DSD_T_InvoiceItem { get; set; }
    }
}
