//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iDeliveryEntity : DbContext
    {
        public iDeliveryEntity()
            : base("name=iDeliveryEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DSD_M_DeliveryHeader> DSD_M_DeliveryHeader { get; set; }
        public DbSet<DSD_M_DeliveryItem> DSD_M_DeliveryItem { get; set; }
        public DbSet<DSD_M_DeliveryOrder> DSD_M_DeliveryOrder { get; set; }
        public DbSet<DSD_M_OrgSystemConfig> DSD_M_OrgSystemConfig { get; set; }
        public DbSet<DSD_M_ShipmentFinance> DSD_M_ShipmentFinance { get; set; }
        public DbSet<DSD_M_ShipmentHeader> DSD_M_ShipmentHeader { get; set; }
        public DbSet<DSD_M_ShipmentHelper> DSD_M_ShipmentHelper { get; set; }
        public DbSet<DSD_M_ShipmentItem> DSD_M_ShipmentItem { get; set; }
        public DbSet<DSD_M_ShipmentVanSalesRoute> DSD_M_ShipmentVanSalesRoute { get; set; }
        public DbSet<DSD_M_SystemConfig> DSD_M_SystemConfig { get; set; }
        public DbSet<DSD_M_Truck> DSD_M_Truck { get; set; }
        public DbSet<DSD_M_TruckCheckAssign> DSD_M_TruckCheckAssign { get; set; }
        public DbSet<DSD_M_TruckCheckList> DSD_M_TruckCheckList { get; set; }
        public DbSet<DSD_M_TruckDriver> DSD_M_TruckDriver { get; set; }
        public DbSet<DSD_T_ARCollection> DSD_T_ARCollection { get; set; }
        public DbSet<DSD_T_ARInvoice> DSD_T_ARInvoice { get; set; }
        public DbSet<DSD_T_DayTimeTracking> DSD_T_DayTimeTracking { get; set; }
        public DbSet<DSD_T_DeliveryBilling> DSD_T_DeliveryBilling { get; set; }
        public DbSet<DSD_T_DeliveryHeader> DSD_T_DeliveryHeader { get; set; }
        public DbSet<DSD_T_DeliveryItem> DSD_T_DeliveryItem { get; set; }
        public DbSet<DSD_T_Invoice> DSD_T_Invoice { get; set; }
        public DbSet<DSD_T_InvoiceItem> DSD_T_InvoiceItem { get; set; }
        public DbSet<DSD_T_OdometerTracking> DSD_T_OdometerTracking { get; set; }
        public DbSet<DSD_T_Payment> DSD_T_Payment { get; set; }
        public DbSet<DSD_T_ShipmentAssign> DSD_T_ShipmentAssign { get; set; }
        public DbSet<DSD_T_ShipmentFinance> DSD_T_ShipmentFinance { get; set; }
        public DbSet<DSD_T_ShipmentHeader> DSD_T_ShipmentHeader { get; set; }
        public DbSet<DSD_T_ShipmentHelper> DSD_T_ShipmentHelper { get; set; }
        public DbSet<DSD_T_ShipmentItem> DSD_T_ShipmentItem { get; set; }
        public DbSet<DSD_T_TruckCheckResult> DSD_T_TruckCheckResult { get; set; }
        public DbSet<DSD_T_TruckStock> DSD_T_TruckStock { get; set; }
        public DbSet<DSD_T_TruckStockTracking> DSD_T_TruckStockTracking { get; set; }
        public DbSet<MD_Account> MD_Account { get; set; }
        public DbSet<MD_AccountAR> MD_AccountAR { get; set; }
        public DbSet<MD_Company> MD_Company { get; set; }
        public DbSet<MD_Contact> MD_Contact { get; set; }
        public DbSet<MD_Dictionary> MD_Dictionary { get; set; }
        public DbSet<MD_Organization> MD_Organization { get; set; }
        public DbSet<MD_Person> MD_Person { get; set; }
        public DbSet<MD_ProdListConfig> MD_ProdListConfig { get; set; }
        public DbSet<MD_Product> MD_Product { get; set; }
        public DbSet<MD_ProductUOM> MD_ProductUOM { get; set; }
        public DbSet<MD_User> MD_User { get; set; }
        public DbSet<MD_Warehouse> MD_Warehouse { get; set; }
        public DbSet<SyncLog> SyncLogs { get; set; }
        public DbSet<Sys_Module> Sys_Module { get; set; }
        public DbSet<Sys_ModuleConfiguration> Sys_ModuleConfiguration { get; set; }
        public DbSet<Sys_Role> Sys_Role { get; set; }
        public DbSet<Sys_UserRoleLink> Sys_UserRoleLink { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<DSD_T_ShipmentVanSalesRoute> DSD_T_ShipmentVanSalesRoute { get; set; }
        public DbSet<DSD_T_Visit> DSD_T_Visit { get; set; }
    }
}
