//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_AccountAR
    {
        public string ID { get; set; }
        public string ebMobile__AccountID__c { get; set; }
        public string ebMobile__Number__c { get; set; }
        public Nullable<bool> ebMobile__IsActive__c { get; set; }
        public Nullable<bool> BatchDeleteFlag__c { get; set; }
        public Nullable<bool> ebMobile__BlockByCredit__c { get; set; }
        public Nullable<decimal> ebMobile__AvailableBalance__c { get; set; }
        public Nullable<decimal> ebMobile__CreditLimit__c { get; set; }
        public Nullable<System.DateTime> ebMobile__DeliveryDate__c { get; set; }
        public string ebMobile__DeliveryDocumentNumber__c { get; set; }
        public string ebMobile__ExternalID__c { get; set; }
        public Nullable<System.Guid> ebMobile__GUID__c { get; set; }
        public Nullable<decimal> ebMobile__InvestmentValue__c { get; set; }
        public Nullable<decimal> ebMobile__InvoiceAmount__c { get; set; }
        public Nullable<System.DateTime> ebMobile__InvoiceDate__c { get; set; }
        public Nullable<System.DateTime> ebMobile__InvoiceDueDate__c { get; set; }
        public string ebMobile__InvoiceNumber__c { get; set; }
        public Nullable<System.DateTime> ebMobile__LastPayment__c { get; set; }
        public Nullable<decimal> ebMobile__OpenAmount__c { get; set; }
        public Nullable<decimal> ebMobile__PastOverDue__c { get; set; }
        public Nullable<System.DateTime> ebMobile__PaymentDate__c { get; set; }
        public Nullable<decimal> ebMobile__RecordAction__c { get; set; }
        public string ebMobile__Remarks__c { get; set; }
        public string SalesRoute__c { get; set; }
        public string ebMobile__ShipToAccountNumber__c { get; set; }
        public Nullable<decimal> ebMobile__TotalOpenAmount__c { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    }
}
