//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_Organization
    {
        public MD_Organization()
        {
            this.DSD_M_OrgSystemConfig = new HashSet<DSD_M_OrgSystemConfig>();
            this.MD_Person = new HashSet<MD_Person>();
            this.MD_ProdListConfig = new HashSet<MD_ProdListConfig>();
        }
    
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        public Nullable<bool> Valid { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual ICollection<DSD_M_OrgSystemConfig> DSD_M_OrgSystemConfig { get; set; }
        public virtual ICollection<MD_Person> MD_Person { get; set; }
        public virtual ICollection<MD_ProdListConfig> MD_ProdListConfig { get; set; }
    }
}
