//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_Product
    {
        public MD_Product()
        {
            this.DSD_M_DeliveryItem = new HashSet<DSD_M_DeliveryItem>();
            this.DSD_M_ShipmentItem = new HashSet<DSD_M_ShipmentItem>();
            this.DSD_T_DeliveryItem = new HashSet<DSD_T_DeliveryItem>();
            this.DSD_T_InvoiceItem = new HashSet<DSD_T_InvoiceItem>();
            this.DSD_T_TruckStock = new HashSet<DSD_T_TruckStock>();
            this.MD_ProductUOM = new HashSet<MD_ProductUOM>();
        }
    
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string DisplayUrl { get; set; }
        public string ExternalDataSource { get; set; }
        public string ExternalId { get; set; }
        public string LastModifiedBy { get; set; }
        public string ProductCode { get; set; }
        public string Description { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string QuantityUnitOfMeasure { get; set; }
        public string ebMobile__BaseUOM__c { get; set; }
        public string ebMobile__BeverageCategory__c { get; set; }
        public string ebMobile__BeverageProduct__c { get; set; }
        public string ebMobile__BeverageType__c { get; set; }
        public string ebMobile__Brand__c { get; set; }
        public string ebMobile__CarbonationIndicator__c { get; set; }
        public string ebMobile__Category__c { get; set; }
        public string ebMobile__Category1__c { get; set; }
        public string ebMobile__Category2__c { get; set; }
        public string ebMobile__Category3__c { get; set; }
        public string ebMobile__Pack1__c { get; set; }
        public string ebMobile__Pack2__c { get; set; }
        public Nullable<decimal> ConversionRate__c { get; set; }
        public string ebMobile__DeliveringPlant__c { get; set; }
        public Nullable<decimal> ebMobile__Denominator__c { get; set; }
        public string ebMobile__DistributionChannel__c { get; set; }
        public string ebMobile__ErpProductCode__c { get; set; }
        public string ebMobile__Flavor__c { get; set; }
        public Nullable<System.Guid> ebMobile__GUID__c { get; set; }
        public string ebMobile__IndSector__c { get; set; }
        public string ebMobile__IANumber__c { get; set; }
        public bool ebMobile__IsEmpty__c { get; set; }
        public string ebMobile__MatFrgtGrp__c { get; set; }
        public string ebMobile__MaterialGroup1__c { get; set; }
        public string ebMobile__MaterialGroup2__c { get; set; }
        public string ebMobile__MaterialGroup3__c { get; set; }
        public string ebMobile__MaterialGroup4__c { get; set; }
        public string ebMobile__MaterialGroup5__c { get; set; }
        public string ebMobile__MaterialPricingGroup__c { get; set; }
        public Nullable<decimal> ebMobile__Numerator__c { get; set; }
        public string ebMobile__OOSFlag__c { get; set; }
        public string ebMobile__Package__c { get; set; }
        public string ebMobile__PackProductID__c { get; set; }
        public string ebMobile__Pack__c { get; set; }
        public string ebMobile__PackType__c { get; set; }
        public string ebMobile__PartProductID__c { get; set; }
        public string ebMobile__PhysicalState__c { get; set; }
        public string ebMobile__Plant__c { get; set; }
        public string ebMobile__PlantDeleteFlag__c { get; set; }
        public string ebMobile__PricingReferenceMaterial__c { get; set; }
        public string ebMobile__ProductGroup__c { get; set; }
        public string ebMobile__PromotionalIndicator__c { get; set; }
        public Nullable<decimal> ebMobile__RecordAction__c { get; set; }
        public string ebMobile__PlRefMat__c { get; set; }
        public string ebMobile__ReturnablePackagingIndicator__c { get; set; }
        public string ebMobile__SalesOrg__c { get; set; }
        public string ebMobile__SalesUnit__c { get; set; }
        public string ebMobile__SalStatus__c { get; set; }
        public Nullable<decimal> ebMobile__Sequence__c { get; set; }
        public string ebMobile__SFAGroup__c { get; set; }
        public string ebMobile__TaxClass__c { get; set; }
        public string ebMobile__TaxType__c { get; set; }
        public string ebMobile__Trademark__c { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual ICollection<DSD_M_DeliveryItem> DSD_M_DeliveryItem { get; set; }
        public virtual ICollection<DSD_M_ShipmentItem> DSD_M_ShipmentItem { get; set; }
        public virtual ICollection<DSD_T_DeliveryItem> DSD_T_DeliveryItem { get; set; }
        public virtual ICollection<DSD_T_InvoiceItem> DSD_T_InvoiceItem { get; set; }
        public virtual ICollection<DSD_T_TruckStock> DSD_T_TruckStock { get; set; }
        public virtual ICollection<MD_ProductUOM> MD_ProductUOM { get; set; }
    }
}
