//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_ProductUOM
    {
        public string Id { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public string Owner { get; set; }
        public string Name { get; set; }
        public string ebMobile__IsActive__c { get; set; }
        public string ebMobile__AlternativeUnit__c { get; set; }
        public Nullable<decimal> ConversionRate__c { get; set; }
        public Nullable<decimal> ebMobile__Denominator__c { get; set; }
        public Nullable<System.Guid> ebMobile__GUID__c { get; set; }
        public string ebMobile__InternationalArticleNumber__c { get; set; }
        public Nullable<decimal> ebMobile__Numerator__c { get; set; }
        public string ebMobile__ParentID__c { get; set; }
        public string ebMobile__ProductID__c { get; set; }
        public string ebMobile__ProductCode__c { get; set; }
        public string ebMobile__SAPKey__c { get; set; }
        public string ebMobile__Size__c { get; set; }
        public Nullable<decimal> ebMobile__UnitPrice__c { get; set; }
        public string ebMobile__UOMCode__c { get; set; }
        public string ebMobile__Weight__c { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual MD_Product MD_Product { get; set; }
    }
}
