//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_Person
    {
        public string UserCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Type { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string WarehouseCode { get; set; }
        public string CompanyCode { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateUser { get; set; }
    
        public virtual MD_Organization MD_Organization { get; set; }
        public virtual MD_User MD_User { get; set; }
    }
}
