//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_User
    {
        public MD_User()
        {
            this.DSD_M_ShipmentHeader = new HashSet<DSD_M_ShipmentHeader>();
            this.DSD_M_ShipmentHeader1 = new HashSet<DSD_M_ShipmentHeader>();
            this.DSD_M_ShipmentHelper = new HashSet<DSD_M_ShipmentHelper>();
            this.DSD_M_TruckDriver = new HashSet<DSD_M_TruckDriver>();
            this.DSD_T_DayTimeTracking = new HashSet<DSD_T_DayTimeTracking>();
            this.DSD_T_ShipmentAssign = new HashSet<DSD_T_ShipmentAssign>();
            this.DSD_T_ShipmentHeader = new HashSet<DSD_T_ShipmentHeader>();
            this.DSD_T_ShipmentHelper = new HashSet<DSD_T_ShipmentHelper>();
            this.Sys_UserRoleLink = new HashSet<Sys_UserRoleLink>();
            this.DSD_T_Visit = new HashSet<DSD_T_Visit>();
        }
    
        public string UserCode { get; set; }
        public string Password { get; set; }
        public bool NeedChangePassword { get; set; }
        public Nullable<System.DateTime> LastChangePassword { get; set; }
        public bool IsValid { get; set; }
        public bool IsLock { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public int LoginFailed { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateUser { get; set; }
    
        public virtual ICollection<DSD_M_ShipmentHeader> DSD_M_ShipmentHeader { get; set; }
        public virtual ICollection<DSD_M_ShipmentHeader> DSD_M_ShipmentHeader1 { get; set; }
        public virtual ICollection<DSD_M_ShipmentHelper> DSD_M_ShipmentHelper { get; set; }
        public virtual ICollection<DSD_M_TruckDriver> DSD_M_TruckDriver { get; set; }
        public virtual ICollection<DSD_T_DayTimeTracking> DSD_T_DayTimeTracking { get; set; }
        public virtual ICollection<DSD_T_ShipmentAssign> DSD_T_ShipmentAssign { get; set; }
        public virtual ICollection<DSD_T_ShipmentHeader> DSD_T_ShipmentHeader { get; set; }
        public virtual ICollection<DSD_T_ShipmentHelper> DSD_T_ShipmentHelper { get; set; }
        public virtual MD_Person MD_Person { get; set; }
        public virtual ICollection<Sys_UserRoleLink> Sys_UserRoleLink { get; set; }
        public virtual ICollection<DSD_T_Visit> DSD_T_Visit { get; set; }
    }
}
