//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_Warehouse
    {
        public MD_Warehouse()
        {
            this.DSD_M_ShipmentHeader = new HashSet<DSD_M_ShipmentHeader>();
            this.DSD_T_ShipmentHeader = new HashSet<DSD_T_ShipmentHeader>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool Valid { get; set; }
        public string Barcode { get; set; }
        public string Remark { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual ICollection<DSD_M_ShipmentHeader> DSD_M_ShipmentHeader { get; set; }
        public virtual ICollection<DSD_T_ShipmentHeader> DSD_T_ShipmentHeader { get; set; }
        public virtual MD_Company MD_Company { get; set; }
    }
}
