//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Role
    {
        public Sys_Role()
        {
            this.Sys_UserRoleLink = new HashSet<Sys_UserRoleLink>();
        }
    
        public int RoleID { get; set; }
        public string Name { get; set; }
        public bool DeleteFlag { get; set; }
        public string Description { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string Modifier { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    
        public virtual ICollection<Sys_UserRoleLink> Sys_UserRoleLink { get; set; }
    }
}
