//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ModuleConfiguration
    {
        public int ModuleConfigurationID { get; set; }
        public int RoleID { get; set; }
        public int ModuleID { get; set; }
        public string Action { get; set; }
        public string Parameters { get; set; }
        public bool Activated { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string Modifier { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    }
}
