//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mde.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UserRoleLink
    {
        public string UserCode { get; set; }
        public int RoleID { get; set; }
        public bool DeleteFlag { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string Modifier { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    
        public virtual MD_User MD_User { get; set; }
        public virtual Sys_Role Sys_Role { get; set; }
    }
}
